version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:2022.04.2
    steps:
      - checkout
      - run:
          name: Installing AWS CLI
          command: |
            sudo apt-get update
            sudo apt install python3-pip
            sudo pip3 install awsebcli --upgrade
      - run: cd ./ && npm install && npm run build && npm run lint --silent
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    machine:
      image: ubuntu-2004:2022.04.2
    steps:
      - attach_workspace:
          at: .
      - checkout
      - run: cd ./ && npm run test
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    machine:
        image: ubuntu-2004:2022.04.2
    steps:
      - attach_workspace:
          at: .
      - checkout
      - run: aws s3 sync ./build s3://circlecidemo
workflows:
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
